# MYSQL
- name: copy my.cnf file
  template: dest=/etc/mysql/my.cnf src=production/files/database/my.cnf-master

- name: db root permissions
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '{{ db_user }}'@'%' WITH GRANT OPTION;"

- name: create classis db
  command: mysql -u {{ db_user }} -e "CREATE DATABASE IF NOT EXISTS {{ db_name }} DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"

- name: copy empty_database.sql to /tmp
  copy: dest=/tmp src=common/files/classis/database.sql

- name: import empty database
  shell: mysql -f -u {{ db_user }} {{ db_name }} < /tmp/database.sql

- name: create classis administrator user
  command: mysql -u {{ db_user }} {{ db_name }} -e "UPDATE users SET passwd=md5('{{ classis_administrator_password }}') WHERE username='administrator';"

- name: generate fees password
  shell: date | md5sum | head -c${1:-10};echo;
  register: fees_pass

- name: generate fees pin
  shell: date | md5sum | head -c${1:-4};echo;
  register: fees_pin

- name: copy fees password
  set_fact:
    classis_fees_password: "fees_password: {{ fees_pass.stdout }}, fees_pin: {{ fees_pin.stdout }}"

- name: save fees password in a file
  copy: dest=/home/{{user}}/classis_fees_passwords content={{ classis_fees_password }}

- name: update fees passwords
  command: mysql -u {{ db_user }} {{ db_name }} -e "UPDATE fees_account SET bankname=AES_ENCRYPT('{{ fees_pass.stdout }}', '{{ fees_pin.stdout }}') WHERE id=1 AND guardian_id=0;"

- name: restart mysql
  service: name=mysql state=restarted
