# MYSQL
- name: Copy my.cnf file
  copy: dest=/etc/mysql/ src=production/files/database/my.cnf.master

- name: Root permissions
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"

- name: Create classis
  command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS classis;"

- name: Restart mysql
  command: service mysql restart