# MYSQL
- name: Copy my.cnf file
  template: dest=/etc/mysql/my.cnf src=production/files/database/my.cnf-master

- name: Db root permissions
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '{{ db_user }}'@'%' WITH GRANT OPTION;"

- name: Create classis db
  command: mysql -u {{ db_user }} -e "CREATE DATABASE IF NOT EXISTS {{ db_name }} DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"

- name: Copy empty_database.sql to /tmp
  copy: dest=/tmp src=common/files/classis/database.sql

- name: Import empty database
  shell: mysql -u {{ db_user }} {{ db_name }} < /tmp/database.sql

- name: Create classis administrator user
  command: mysql -u {{ db_user }} {{ db_name }} -e "UPDATE users SET passwd=md5('{{ classis_administrator_password }}') WHERE username='administrator';"

- service: name=mysql state=restarted
