- name: add apache monitoring html file
  template: dest={{ application_directory }}/monitor.html src=common/files/classis/monitor.html owner={{ user }} group=www-data mode=0775

- name: copy monitoring scripts
  template: dest={{ utils_directory }}/monitoring/ src=common/files/classis/utils/monitoring/{{ item }}
  with_items:
    - apache_monitor
    - disk_space_monitor

- name: add monitoring cron jobs
  template: dest=/etc/cron.d/classis_monitoring src=common/files/classis/utils/monitoring/monitor_cron

- name: restart cron
  service: name=cron state=restarted
