- hosts: all
  user: vagrant
  become: yes
  tasks:
    - include_vars: vars/development.yml
    - include: common/tasks/main.yml
    - include: common/tasks/shell.yml
    - include: development/tasks/database.yml
    - include: common/tasks/php.yml
    - include: common/tasks/pear.yml
    - include: common/tasks/apache.yml
    - include: common/tasks/classis.yml
