# APACHE
# ====================================================
- name: install apache2
  action: apt name=apache2

- name: install libapache2-mod-php5
  action: apt name=libapache2-mod-php5

- name: copy apache config file
  template: dest=/etc/apache2/sites-available/ src=files/apache/{{ apache_site }}.conf

- name: copy phpmyadmin config file
  copy: dest=/etc/apache2/conf-enabled/phpmyadmin.conf src=files/phpmyadmin/phpmyadmin.conf

- name: Enable rewrite
  command: a2enmod rewrite

- name: Restart apache
  command: service apache2 restart

