# APACHE
# ====================================================
- name: install apache2
  apt: name=apache2 state=present

- name: install libapache2-mod-php5
  apt: name=libapache2-mod-php5 state=present

- name: disable site
  command: a2dissite {{ apache_site }}

- name: create base directory
  file: dest={{ base_directory }} state=directory follow=yes owner={{ user }} group=www-data mode=0750 recurse=yes

- name: copy apache config file
  template: dest=/etc/apache2/sites-available/{{ apache_site }} src={{ environ }}/files/apache/{{ apache_site }}

- name: copy phpmyadmin config file
  template: dest=/etc/apache2/conf-enabled/phpmyadmin.conf src=common/files/phpmyadmin/phpmyadmin.conf

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present

- name: enable ssl
  command: a2enmod ssl
  when: ssl == 'on'

- name: enable site
  command: a2ensite {{ apache_site }}

- name: restart apache
  service: name=apache2 state=restarted
