# APACHE
# ====================================================
- name: install apache2
  apt: name=apache2 state=present

- name: install libapache2-mod-php5
  apt: name=libapache2-mod-php5 state=present

- name: copy apache config file
  template: dest=/etc/apache2/sites-available/{{ apache_site }} src={{ environ }}/files/apache/{{ apache_site }}

- name: copy phpmyadmin config file
  template: dest=/etc/apache2/conf-enabled/phpmyadmin.conf src=common/files/phpmyadmin/phpmyadmin.conf

- name: Enable rewrite
  command: a2enmod rewrite

- name: Enable ssl
  command: a2enmod ssl
  when: ssl == 'on'

- name: Enable site
  command: a2ensite {{ apache_site }}

- service: name=apache2 state=restarted

