- name: create application directory
  file: dest={{ application_directory }} state=directory follow=yes owner={{ user }} group=www-data mode=0750 recurse=yes

- name: setup the Classis git repo
  become: no
  git: repo={{ repository  }} dest={{ application_directory }}/{{ classis_directory }} accept_hostkey=yes update=no

- name: copy toplevel images
  command: cp -pr {{ application_directory }}/{{ classis_directory }}/install/toplevel/images {{ application_directory }}/ creates={{ application_directory }}/images

- name: copy toplevel templates
  command: cp -pr {{ application_directory }}/{{ classis_directory }}/install/toplevel/templates {{ application_directory }}/ creates={{ application_directory }}/templates

- name: copy toplevel curriculum
  command: cp -pr {{ application_directory }}/{{ classis_directory }}/install/toplevel/curriculum {{ application_directory }}/ creates={{ application_directory }}/curriculum

- name: copy toplevel schoollang
  command: cp -p {{ application_directory }}/{{ classis_directory }}/install/toplevel/schoollang.php {{ application_directory }}/

- name: copy toplevel schoolarrays
  command: cp -p {{ application_directory }}/{{ classis_directory }}/install/toplevel/schoolarrays.php {{ application_directory }}/

- name: copy toplevel index
  command: cp -p {{ application_directory }}/{{ classis_directory }}/install/toplevel/index.php {{ application_directory }}/

- name: create db_connect
  template: dest={{ application_directory }}/dbh_connect.php src=common/files/classis/config/dbh_connect.php

- name: create school.php
  template: dest={{ application_directory }}/school.php src=common/files/classis/config/school.php

- name: copy default eportfolio directory
  synchronize: dest={{ eportfolio_directory }} src=common/files/classis/eportfolio/ recursive=yes

- name: copy wkhtmltopdf working version to /usr/local/bin
  copy: dest=/usr/local/bin src=common/files/classis/utils/wkhtmltopdf mode=0775

- name: create utils directory
  file: dest={{ utils_directory }} state=directory follow=yes

- name: link School logo
  shell: ln -sf {{ school_logo_path }} {{ application_directory }}/images/schoollogo.png
  when: school_logo_path != ''

- name: set Classis directory permisssions
  file: path={{ application_directory }} state=directory owner={{ user }} group=www-data mode=0750 recurse=yes

- name: set eportfolio directory permisssions
  file: path={{ eportfolio_directory }} state=directory owner=www-data group={{ user }} mode=0775 recurse=yes

- name: set utils directory permisssions
  file: path={{ utils_directory }} state=directory owner={{ user }} group=www-data mode=0750 recurse=yes
