- name: install pear
  apt: name=php-pear state=present

- name: install latest PEAR/PEAR package
  pear: name=PEAR state=latest

- name: install pear packages
  pear: name={{ item }}
  with_items:
    - Archive_Tar-1.3.16
    - Auth_SASL-1.0.6
    - Console_Getopt-1.3.1
    - DB-1.9.2
    - HTTP-1.4.1
    - HTTP_Request2-2.2.1
    - MDB2-2.4.1
    - Mail-1.2.0
    - Mail_Mime-1.8.9
    - Mail_Queue-1.2.7
    - Mail_mimeDecode-1.5.5
    - Math_Combinatorics-1.0.0
    - Net_SMTP-1.6.2
    - Net_Socket-1.0.14
    - Net_URL2-2.2.0
    - OLE-1.0.0RC1
    - Spreadsheet_Excel_Writer-0.9.2
    - Structures_Graph-1.0.4
    - XML_Parser-1.3.2
    - XML_Serializer-0.20.0
    - XML_Util-1.2.3

- name: update htmlpurifier channel.
  command: pear channel-discover htmlpurifier.org
  register: channel_result
  changed_when: "'already initialized' not in channel_result.stdout"
  failed_when: "channel_result.stderr"

- name: install HTMLPurifier PEAR package
  pear: name=hp/HTMLPurifier
