- name: install pear
  action: apt name=php-pear

- pear: name=PEAR state=latest
- pear: name=Archive_Tar-1.3.16
- pear: name=Auth_SASL-1.0.6
- pear: name=Console_Getopt-1.3.1
- pear: name=DB-1.9.2
- pear: name=HTTP-1.4.1
- pear: name=HTTP_Request2-2.2.1
- pear: name=MDB2-2.4.1
- pear: name=Mail-1.2.0
- pear: name=Mail_Mime-1.8.9
- pear: name=Mail_Queue-1.2.7
- pear: name=Mail_mimeDecode-1.5.5
- pear: name=Math_Combinatorics-1.0.0
- pear: name=Net_SMTP-1.6.2
- pear: name=Net_Socket-1.0.14
- pear: name=Net_URL2-2.2.0
- pear: name=OLE-1.0.0RC1
- pear: name=Spreadsheet_Excel_Writer-0.9.2
- pear: name=Structures_Graph-1.0.4
- pear: name=XML_Parser-1.3.2
- pear: name=XML_Serializer-0.20.0
- pear: name=XML_Util-1.2.3

- name: Update htmlpurifier channel.
  command: pear channel-discover htmlpurifier.org
  register: channel_result
  changed_when: "'already initialized' not in channel_result.stdout"
  failed_when: "channel_result.stderr"

- pear: name=hp/HTMLPurifier
