- name: apt-get update
  command: apt-get update

- name: add php5-dev
  action: apt name=php5-dev

- name: add php5-mysql
  action: apt name=php5-mysql

- name: apt-get install php5-mcrypt
  action: apt name=php5-mcrypt

- name: apt-get install php5-curl
  action: apt name=php5-curl

- name: Enable php5-mcrypt
  command: php5enmod mcrypt

- name: install pear
  action: apt name=php-pear

- pear: name=PEAR-1.10.0
- pear: name=Archive_Tar-1.3.16
- pear: name=Auth_SASL-1.0.6
- pear: name=Console_Getopt-1.3.1
- pear: name=DB-1.9.2
- pear: name=HTTP-1.4.1
- pear: name=HTTP_Request2-2.2.1
- pear: name=MDB2-2.4.1
- pear: name=Mail-1.2.0
- pear: name=Mail_Mime-1.8.9
- pear: name=Mail_Queue-1.2.7
- pear: name=Mail_mimeDecode-1.5.5
- pear: name=Math_Combinatorics-1.0.0
- pear: name=Net_SMTP-1.6.2
- pear: name=Net_Socket-1.0.14
- pear: name=Net_URL2-2.2.0
- pear: name=OLE-1.0.0RC1
- pear: name=Spreadsheet_Excel_Writer-0.9.2
- pear: name=Structures_Graph-1.0.4
- pear: name=XML_Parser-1.3.2
- pear: name=XML_Serializer-0.20.0
- pear: name=XML_Util-1.2.3

- name: apt-get install phpmyadmin
  action: apt name=phpmyadmin

- name: copy phpmyadmin config-db file
  copy: dest=/etc/phpmyadmin/config-db.php src=files/phpmyadmin/config-db.php

- name: copy phpmyadmin config.inc.php file
  copy: dest=/etc/phpmyadmin/config.inc.php src=files/phpmyadmin/config.inc.php
