- name: apt-get update
  action: apt update_cache=yes

- name: add php5-dev
  action: apt name=php5

- name: add libapache2-mod-php5
  action: apt name=libapache2-mod-php5

- name: add php5-xsl
  action: apt name=php5-xsl

- name: add php5-mysql
  action: apt name=php5-mysql

- name: apt-get install php5-mcrypt
  action: apt name=php5-mcrypt

- name: apt-get install php5-curl
  action: apt name=php5-curl

- name: Enable php5-mcrypt
  command: php5enmod mcrypt

- name: apt-get install phpmyadmin
  action: apt name=phpmyadmin

- name: copy phpmyadmin config-db file
  template: dest=/etc/phpmyadmin/config-db.php src=common/files/phpmyadmin/config-db.php

- name: copy phpmyadmin config.inc.php file
  template: dest=/etc/phpmyadmin/config.inc.php src=common/files/phpmyadmin/config.inc.php
