# MYSQL
- name: copy my.cnf file
  template: dest=/etc/mysql/ src=development/files/database/my.cnf

- name: db root permissions
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '{{ db_user }}'@'%' WITH GRANT OPTION;"

- name: create classis db
  command: mysql -u {{ db_user }} -e "CREATE DATABASE IF NOT EXISTS {{ db_name }} DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"

- name: copy empty_database.sql to /tmp
  copy: dest=/tmp src=common/files/classis/empty_database.sql

- name: import empty database
  shell: mysql -u {{ db_user }} {{ db_name }} < /tmp/empty_database.sql

- name: create classis administrator user
  command: mysql -u {{ db_user }} {{ db_name }} -e "INSERT INTO users (username, passwd, forename, role, firstbookpref)
    SELECT 'administrator', md5('{{ classis_administrator_password }}'), 'administrator', 'admin', 'admin' FROM users
    WHERE NOT EXISTS (SELECT 1 FROM users WHERE username='administrator')"

- name: restart mysql
  service: name=mysql state=restarted
