# MYSQL
- name: Install MySQL
  action: apt name=mysql-server

- name: copy my.cnf file
  template: dest=/etc/mysql/ src=development/files/database/my.cnf

- name: Root permissions
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"

- name: Create classis db
  command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS classis;"

- service: name=mysql state=restarted
